server:
  port: 8088
  servlet:
    context-path: /gira

spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver

spring-doc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem